module.exports = [
  {
    name: 'vue3+vite+ts+vitest模板',
    npmName: '@yaotou/template-vue3',
    version: '1.1.4',
    type: 'normal',
    installCommand: 'npm install',
    startCommand: 'npm run dev',
    tag: ['project'],
    ejsIgnore: ['**/public/**'],
  },
  {
    name: 'vue3+vite+ts+NaiveUI 后台管理项目',
    npmName: '@yaotou/template-vue3-admin',
    version: '^1.0.0',
    type: 'normal',
    tag: ['project'],
    installCommand: 'npm install',
    startCommand: 'npm run dev',
    ejsIgnore: ['**/public/**'],
  },
  {
    name: 'vue3+components模板',
    npmName: '@yaotou/template-vue3-component',
    version: '1.1.4',
    type: 'normal',
    installCommand: 'npm install --registry https://registry.npm.taobao.org',
    startCommand: 'npm run serve',
    tag: ['components'],
    ejsIgnore: ['**/public/**', '**.png'],
  },
  {
    name: 'vue3+vite+ts+vitest自定义模板',
    npmName: '@yaotou/custom-template-vue3',
    version: '1.1.4',
    type: 'custom',
    installCommand: 'npm install',
    startCommand: 'npm run dev',
    tag: ['project'],
    ejsIgnore: ['**/public/**'],
  },
];
